ANDROID_TARGET_SDK="platforms;android-27"
ANDROID_BUILD_TOOLS="build-tools;27.0.3"
sudo sdk/tools/bin/sdkmanager "platform-tools" "${ANDROID_TARGET_SDK}" "${ANDROID_BUILD_TOOLS}"

ANDROID_BUILD_TOOLS="build-tools;28.0.3"
sudo sdk/tools/bin/sdkmanager "platform-tools" "${ANDROID_BUILD_TOOLS}"

ANDROID_TARGET_SDK="platforms;android-25"
ANDROID_BUILD_TOOLS="build-tools;25.0.3"
ANDROID_SDK_TOOLS="25.2.3"
ANDROID_IMAGE1="system-images;android-24;default;arm64-v8a"
ANDROID_IMAGE2="system-images;android-24;default;armeabi-v7a"
ANDROID_IMAGE3="system-images;android-24;default;x86_64"
sudo sdk/tools/bin/sdkmanager "platform-tools" "${ANDROID_TARGET_SDK}" "${ANDROID_BUILD_TOOLS}"
sudo sdk/tools/bin/sdkmanager "extras;android;m2repository" "extras;google;m2repository"
sudo sdk/tools/bin/sdkmanager "emulator" "${ANDROID_IMAGE1}" "${ANDROID_IMAGE2}" "${ANDROID_IMAGE3}"
